#!/usr/bin/env python3
"""Convert a config string like "A=1 B=foo C='bar baz'" into bash exports.

This is intentionally conservative to avoid arbitrary code execution:
- Only parses shell-like tokens (shlex.split)
- Only accepts KEY=VAL pairs where KEY matches [A-Z_][A-Z0-9_]*

Usage:
  python3 scripts/config_str_to_exports.py --config "LOH_ENABLE_RL=0 LOH_USE_SOFTMAX=1"
  python3 scripts/config_str_to_exports.py --config-file path/to/config.txt
"""

from __future__ import annotations

import argparse
import re
import shlex
import sys
from pathlib import Path


_RE_KEY = re.compile(r"^[A-Z_][A-Z0-9_]*$")


def _bash_single_quote(value: str) -> str:
    # Safely single-quote for bash: ' -> '\''
    return "'" + value.replace("'", "'\\''") + "'"


def _iter_kv_tokens(config: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    if not config.strip():
        return out

    try:
        tokens = shlex.split(config, posix=True)
    except ValueError as e:
        raise SystemExit(f"[config_str_to_exports] Failed to parse config string: {e}")

    for tok in tokens:
        if "=" not in tok:
            continue
        key, val = tok.split("=", 1)
        if not _RE_KEY.match(key):
            continue
        out.append((key, val))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--config", type=str, help="Config string: space-separated KEY=VAL tokens")
    g.add_argument("--config-file", type=str, help="Path to a text file containing a config string")
    ap.add_argument(
        "--comment-prefix",
        type=str,
        default="# ",
        help="Prefix for comment lines (printed to stdout).",
    )
    args = ap.parse_args()

    if args.config_file:
        p = Path(args.config_file)
        if not p.exists():
            print(f"[config_str_to_exports] Config file not found: {p}", file=sys.stderr)
            return 2
        config = p.read_text(encoding="utf-8", errors="replace").strip()
    else:
        config = (args.config or "").strip()

    kvs = _iter_kv_tokens(config)
    print(f"{args.comment_prefix}generated by scripts/config_str_to_exports.py")
    print(f"{args.comment_prefix}input_tokens={len(shlex.split(config, posix=True)) if config else 0} kv_pairs={len(kvs)}")
    for k, v in kvs:
        print(f"export {k}={_bash_single_quote(v)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
