#!/usr/bin/env python3
"""Merge two generated AC reward-signal Markdown reports without rescanning logs.

Use case:
- You already have a stats-rich report generated by scanning logs (slow).
- You also have a config-rich report generated in header-only mode (fast).
- You want a single combined Markdown that includes BOTH:
  - per-file cfg/params (from config-rich)
  - per-file reward/penalty distributions/statistics (from stats-rich)

This script does NOT read any .log files.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


RE_SCALE = re.compile(r"^##\s+penalty_scale\s*=\s*(.+?)\s*$")
RE_FILE = re.compile(r"^-\s+\*\*(ac_sb3_[^*]+\.log)\*\*\s*$")


@dataclass
class ScaleBlock:
    summary_lines: List[str]
    file_blocks: Dict[str, List[str]]  # file -> list of markdown lines under it (indented bullets)


@dataclass
class ConfigInfo:
    cfg_line: Optional[str]
    params_line: Optional[str]


def _read_lines(path: str) -> List[str]:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return [ln.rstrip("\n") for ln in f]


def _parse_scales(lines: List[str]) -> Dict[str, ScaleBlock]:
    """Parse a generated report into scale blocks.

    Returns scale -> ScaleBlock(summary_lines, file_blocks).

    summary_lines: the markdown lines between **Summary** and **Files** (inclusive bullets), excluding headers.
    file_blocks[file]: list of lines belonging to that file entry (excluding the '- **file**' line itself).
    """

    by_scale: Dict[str, ScaleBlock] = {}

    current_scale: Optional[str] = None
    in_summary = False
    in_files = False

    current_file: Optional[str] = None

    def ensure_scale(scale: str) -> ScaleBlock:
        if scale not in by_scale:
            by_scale[scale] = ScaleBlock(summary_lines=[], file_blocks={})
        return by_scale[scale]

    for line in lines:
        m = RE_SCALE.match(line)
        if m:
            current_scale = m.group(1).strip()
            ensure_scale(current_scale)
            in_summary = False
            in_files = False
            current_file = None
            continue

        if current_scale is None:
            continue

        if line.strip() == "**Summary**":
            in_summary = True
            in_files = False
            current_file = None
            continue
        if line.strip() == "**Files**":
            in_summary = False
            in_files = True
            current_file = None
            continue

        m = RE_FILE.match(line)
        if m and in_files:
            current_file = m.group(1)
            ensure_scale(current_scale).file_blocks.setdefault(current_file, [])
            continue

        if in_summary:
            # keep list items only; ignore blanks
            if line.startswith("-"):
                ensure_scale(current_scale).summary_lines.append(line)
            continue

        if in_files and current_file is not None:
            # keep bullet/sub-lines under this file
            if line.startswith("  ") or line.startswith("\t"):
                ensure_scale(current_scale).file_blocks[current_file].append(line)
            # ignore blank lines and other headers

    return by_scale


def _extract_manifest(lines: List[str]) -> Tuple[List[str], List[str]]:
    """Return (header_lines, manifest_files).

    header_lines: everything up to and including the File Manifest section.
    manifest_files: list of file paths in the manifest.

    Works for our newer report format.
    """
    header: List[str] = []
    manifest: List[str] = []

    in_manifest = False
    for line in lines:
        header.append(line)
        if line.strip() == "## File Manifest":
            in_manifest = True
            continue
        if in_manifest:
            m = re.match(r"^-\s+(ac_sb3_\S+\.log)\s*$", line)
            if m:
                manifest.append(m.group(1))
            # stop when we hit the first scale section
            if line.startswith("## penalty_scale"):
                # remove this scale header from header
                header.pop()
                break

    return header, manifest


def _parse_config_info(config_scale_blocks: Dict[str, ScaleBlock]) -> Dict[str, ConfigInfo]:
    out: Dict[str, ConfigInfo] = {}
    for scale, sb in config_scale_blocks.items():
        for file, lines in sb.file_blocks.items():
            cfg_line = None
            params_line = None
            for ln in lines:
                s = ln.strip()
                if s.startswith("- cfg:"):
                    cfg_line = ln
                elif s.startswith("- params:"):
                    params_line = ln
            out[file] = ConfigInfo(cfg_line=cfg_line, params_line=params_line)
    return out


def _filter_out_params(lines: List[str]) -> List[str]:
    out: List[str] = []
    for ln in lines:
        if ln.strip().startswith("- params:"):
            continue
        if ln.strip().startswith("- cfg:"):
            # cfg from stats report is usually missing/less reliable; we will use config version.
            continue
        out.append(ln)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stats", required=True, help="Stats-rich report path (already scanned logs)")
    ap.add_argument("--config", required=True, help="Config-rich report path (header-only)")
    ap.add_argument("--out", required=True, help="Output combined report path")
    args = ap.parse_args()

    stats_lines = _read_lines(args.stats)
    config_lines = _read_lines(args.config)

    stats_scales = _parse_scales(stats_lines)
    config_scales = _parse_scales(config_lines)

    config_header, manifest = _extract_manifest(config_lines)
    config_info = _parse_config_info(config_scales)

    # Prefer the stats report scale ordering (sorted by key for stability)
    combined: List[str] = []

    # Header: take config header (has Inputs + File Manifest)
    combined.extend(["# AC Reward/Penalty Signal Combined Report", ""])
    combined.append("This file is created by merging:")
    combined.append(f"- stats: {args.stats}")
    combined.append(f"- config: {args.config}")
    combined.append("")

    combined.extend(config_header)
    combined.append("")

    # If stats had an overall files/filter line near top, we keep a short hint
    combined.append("## Notes")
    combined.append("")
    combined.append("- Distributions/statistics come from the stats report (no log rescanning here).")
    combined.append("- cfg/params come from the config report when available.")
    combined.append("")

    for scale in sorted(stats_scales.keys()):
        sb = stats_scales[scale]
        combined.append(f"## penalty_scale = {scale}")
        combined.append("")
        if sb.summary_lines:
            combined.append("**Summary**")
            combined.extend(sb.summary_lines)
            combined.append("")

        combined.append("**Files**")
        combined.append("")

        for file in sorted(sb.file_blocks.keys()):
            combined.append(f"- **{file}**")
            ci = config_info.get(file)
            if ci and ci.cfg_line:
                combined.append(ci.cfg_line)
            if ci and ci.params_line:
                combined.append(ci.params_line)
            else:
                # fall back to stats report params line if config missing
                for ln in sb.file_blocks[file]:
                    if ln.strip().startswith("- params:"):
                        combined.append(ln)
                        break

            # add all remaining stats bullets except params/cfg
            combined.extend(_filter_out_params(sb.file_blocks[file]))
            combined.append("")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(combined).rstrip() + "\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
